name: test

on:
  push:
    branches:
      - test-faster-mirror
      - 'release/**'
  pull_request:

jobs:
  test-cgroup2:
    name: "cgroup2"
    # nested virtualization is only available on macOS hosts
    runs-on: macos-10.15
    timeout-minutes: 40
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    # Vagrant is slow, so we build binaries outside Vagrant
    - name: "Boot VM"
      run: |
        vagrant up
        vagrant ssh-config >> ~/.ssh/config
    - name: "Get faster C"
      run: |
        cat script.sh | ssh default -- 'tee script.sh && chmod +x script.sh && ./script.sh'
    - name: "Run tests"
      # TODO: enable -test.kill-daemon, after Fedora updates containerd to a recent version (Mar 2021)
      run: ssh default -- "sudo /vagrant/nerdctl.test -test.v"
    - name: "Install rootless containerd"
      run: |
        ssh default -- containerd-rootless-setuptool.sh install
        ssh default -- containerd-rootless-setuptool.sh install-fuse-overlayfs
    - name: "Run tests (rootless)"
      run: ssh default -- "CONTAINERD_SNAPSHOTTER=fuse-overlayfs /vagrant/nerdctl.test -test.v -test.kill-daemon"
    - name: "Uninstall rootless containerd"
      run: ssh default -- containerd-rootless-setuptool.sh uninstall
